org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=false

android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

reactNativeArchitectures=arm64-v8a,armeabi-v7a
newArchEnabled=false
hermesEnabled=true